name: project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flex_color_scheme: ^8.1.1
  flutter:
    sdk: flutter
  get: ^4.7.2
  sqflite: ^2.4.1
  supabase_flutter: ^2.8.3
  path:
  skeletonizer: ^1.4.3
  file_picker: ^10.1.2
  url_launcher: ^6.3.1
  permission_handler: ^12.0.0+1
  connectivity_plus: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
