

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pgsodium";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."get_student_invoice_data"("term_input" "text", "amount" numeric, "desc_text" "text") RETURNS TABLE("sid" integer, "description" "text", "invoiceamount" numeric, "term" "text")
    LANGUAGE "plpgsql"
    AS $$
BEGIN
    RETURN QUERY
    WITH Class_Credit_Hours AS (
        SELECT
            c."id",
            SUM(co."credits") AS totalCreditHours
        FROM
            "Class" c  -- ✅ Use double quotes for correct case
        JOIN "Course" co ON c."courseId" = co."id"
        WHERE
            c."term" = term_input  -- ✅ Use double quotes for column names
        GROUP BY
            c."id"
    ),
    Student_Invoice_Data AS (
        SELECT
            s."id"::INT as student_sid,
            cch.totalCreditHours,
            (cch.totalCreditHours * amount) AS student_invoice_amount,
            c."term" AS class_term
        FROM
            "Enrollment" e
        JOIN "Student" s ON e."studentId" = s."id"
        JOIN Class_Credit_Hours cch ON e."classId" = cch."id"
        JOIN "Class" c ON e."classId" = c."id"
        WHERE
            c."term" = term_input
    )
    SELECT
        student_sid AS sid,
        desc_text AS description,
        student_invoice_amount AS invoiceAmount,
        class_term AS term
    FROM
        Student_Invoice_Data;
END;
$$;


ALTER FUNCTION "public"."get_student_invoice_data"("term_input" "text", "amount" numeric, "desc_text" "text") OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."Admin" (
    "id" bigint NOT NULL,
    "userId" "uuid" NOT NULL
);


ALTER TABLE "public"."Admin" OWNER TO "postgres";


ALTER TABLE "public"."Admin" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Admin_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Assessment" (
    "id" bigint NOT NULL,
    "title" "text" NOT NULL,
    "description" "text" NOT NULL,
    "deadline" timestamp with time zone NOT NULL,
    "max" integer NOT NULL,
    "weight" integer NOT NULL,
    "type" "text" NOT NULL,
    "classId" bigint
);


ALTER TABLE "public"."Assessment" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."AssessmentFile" (
    "id" bigint NOT NULL,
    "assessmentId" bigint NOT NULL,
    "name" "text" NOT NULL,
    "url" "text"
);


ALTER TABLE "public"."AssessmentFile" OWNER TO "postgres";


ALTER TABLE "public"."AssessmentFile" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."AssessmentFile_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."Assessment" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Assessment_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Attendance" (
    "id" bigint NOT NULL,
    "present" boolean DEFAULT true NOT NULL,
    "studentId" bigint NOT NULL,
    "scheduleId" bigint NOT NULL
);


ALTER TABLE "public"."Attendance" OWNER TO "postgres";


ALTER TABLE "public"."Attendance" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Attendance_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Class" (
    "id" bigint NOT NULL,
    "teacherId" bigint NOT NULL,
    "courseId" bigint NOT NULL,
    "term" "text" NOT NULL,
    "section" "text" NOT NULL
);


ALTER TABLE "public"."Class" OWNER TO "postgres";


ALTER TABLE "public"."Class" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Class_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Course" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "mode" "text" NOT NULL,
    "credits" smallint DEFAULT '3'::smallint NOT NULL
);


ALTER TABLE "public"."Course" OWNER TO "postgres";


ALTER TABLE "public"."Course" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Course_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Department" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL
);


ALTER TABLE "public"."Department" OWNER TO "postgres";


ALTER TABLE "public"."Department" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Department_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Enrollment" (
    "id" bigint NOT NULL,
    "studentId" bigint NOT NULL,
    "classId" bigint NOT NULL
);


ALTER TABLE "public"."Enrollment" OWNER TO "postgres";


ALTER TABLE "public"."Enrollment" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Enrollment_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Invoice" (
    "id" bigint NOT NULL,
    "description" "text" DEFAULT 'Misc. Fee'::"text" NOT NULL,
    "amount" numeric NOT NULL,
    "dueDate" timestamp with time zone NOT NULL,
    "paidDate" timestamp with time zone,
    "term" "text" NOT NULL,
    "studentId" bigint NOT NULL
);


ALTER TABLE "public"."Invoice" OWNER TO "postgres";


ALTER TABLE "public"."Invoice" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Invoice_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Program" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "level" "text" NOT NULL,
    "totalCredit" smallint NOT NULL,
    "departmentId" bigint NOT NULL
);


ALTER TABLE "public"."Program" OWNER TO "postgres";


ALTER TABLE "public"."Program" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Program_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Request" (
    "id" bigint NOT NULL,
    "studentId" bigint NOT NULL,
    "classId" bigint NOT NULL,
    "approved" boolean
);


ALTER TABLE "public"."Request" OWNER TO "postgres";


ALTER TABLE "public"."Request" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Request_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Schedule" (
    "id" bigint NOT NULL,
    "classId" bigint NOT NULL,
    "startTime" timestamp with time zone NOT NULL,
    "endTime" timestamp with time zone NOT NULL,
    "venue" "text" NOT NULL
);


ALTER TABLE "public"."Schedule" OWNER TO "postgres";


ALTER TABLE "public"."Schedule" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Schedule_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Student" (
    "id" bigint NOT NULL,
    "rollNo" "text" NOT NULL,
    "userId" "uuid" NOT NULL,
    "programId" bigint NOT NULL
);


ALTER TABLE "public"."Student" OWNER TO "postgres";


ALTER TABLE "public"."Student" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Student_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Submission" (
    "id" bigint NOT NULL,
    "marks" integer,
    "studentId" bigint NOT NULL,
    "assessmentId" bigint NOT NULL
);


ALTER TABLE "public"."Submission" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."SubmissionFile" (
    "id" bigint NOT NULL,
    "submissionId" bigint NOT NULL,
    "name" "text" NOT NULL,
    "url" "text"
);


ALTER TABLE "public"."SubmissionFile" OWNER TO "postgres";


ALTER TABLE "public"."SubmissionFile" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."SubmissionFile_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."Submission" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Submission_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."Teacher" (
    "id" bigint NOT NULL,
    "position" "text" NOT NULL,
    "office" "text" DEFAULT 'Visiting'::"text" NOT NULL,
    "userId" "uuid" NOT NULL
);


ALTER TABLE "public"."Teacher" OWNER TO "postgres";


ALTER TABLE "public"."Teacher" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Teacher_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."User" (
    "id" "uuid" NOT NULL,
    "name" "text" NOT NULL,
    "address" "text" NOT NULL,
    "dob" "date",
    "departmentId" bigint NOT NULL,
    "role" smallint DEFAULT '1'::smallint NOT NULL
);


ALTER TABLE "public"."User" OWNER TO "postgres";


ALTER TABLE ONLY "public"."Admin"
    ADD CONSTRAINT "Admin_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."AssessmentFile"
    ADD CONSTRAINT "AssessmentFile_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Assessment"
    ADD CONSTRAINT "Assessment_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Attendance"
    ADD CONSTRAINT "Attendance_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Class"
    ADD CONSTRAINT "Class_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Course"
    ADD CONSTRAINT "Course_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Department"
    ADD CONSTRAINT "Department_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Enrollment"
    ADD CONSTRAINT "Enrollment_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Invoice"
    ADD CONSTRAINT "Invoice_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Program"
    ADD CONSTRAINT "Program_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Request"
    ADD CONSTRAINT "Request_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Schedule"
    ADD CONSTRAINT "Schedule_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Student"
    ADD CONSTRAINT "Student_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."SubmissionFile"
    ADD CONSTRAINT "SubmissionFile_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Submission"
    ADD CONSTRAINT "Submission_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Teacher"
    ADD CONSTRAINT "Teacher_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."User"
    ADD CONSTRAINT "User_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."Admin"
    ADD CONSTRAINT "Admin_userId_fkey" FOREIGN KEY ("userId") REFERENCES "public"."User"("id");



ALTER TABLE ONLY "public"."AssessmentFile"
    ADD CONSTRAINT "AssessmentFile_assessmentId_fkey" FOREIGN KEY ("assessmentId") REFERENCES "public"."Assessment"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."Assessment"
    ADD CONSTRAINT "Assessment_classId_fkey" FOREIGN KEY ("classId") REFERENCES "public"."Class"("id");



ALTER TABLE ONLY "public"."Attendance"
    ADD CONSTRAINT "Attendance_scheduleId_fkey" FOREIGN KEY ("scheduleId") REFERENCES "public"."Schedule"("id");



ALTER TABLE ONLY "public"."Attendance"
    ADD CONSTRAINT "Attendance_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "public"."Student"("id");



ALTER TABLE ONLY "public"."Class"
    ADD CONSTRAINT "Class_courseId_fkey" FOREIGN KEY ("courseId") REFERENCES "public"."Course"("id");



ALTER TABLE ONLY "public"."Class"
    ADD CONSTRAINT "Class_teacherId_fkey" FOREIGN KEY ("teacherId") REFERENCES "public"."Teacher"("id");



ALTER TABLE ONLY "public"."Enrollment"
    ADD CONSTRAINT "Enrollment_classId_fkey" FOREIGN KEY ("classId") REFERENCES "public"."Class"("id");



ALTER TABLE ONLY "public"."Enrollment"
    ADD CONSTRAINT "Enrollment_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "public"."Student"("id");



ALTER TABLE ONLY "public"."Invoice"
    ADD CONSTRAINT "Invoice_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "public"."Student"("id");



ALTER TABLE ONLY "public"."Program"
    ADD CONSTRAINT "Program_departmentId_fkey" FOREIGN KEY ("departmentId") REFERENCES "public"."Department"("id");



ALTER TABLE ONLY "public"."Request"
    ADD CONSTRAINT "Request_classId_fkey" FOREIGN KEY ("classId") REFERENCES "public"."Class"("id");



ALTER TABLE ONLY "public"."Request"
    ADD CONSTRAINT "Request_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "public"."Student"("id");



ALTER TABLE ONLY "public"."Schedule"
    ADD CONSTRAINT "Schedule_classId_fkey" FOREIGN KEY ("classId") REFERENCES "public"."Class"("id");



ALTER TABLE ONLY "public"."Student"
    ADD CONSTRAINT "Student_programId_fkey" FOREIGN KEY ("programId") REFERENCES "public"."Program"("id");



ALTER TABLE ONLY "public"."Student"
    ADD CONSTRAINT "Student_userId_fkey" FOREIGN KEY ("userId") REFERENCES "public"."User"("id");



ALTER TABLE ONLY "public"."SubmissionFile"
    ADD CONSTRAINT "SubmissionFile_submissionId_fkey" FOREIGN KEY ("submissionId") REFERENCES "public"."Submission"("id");



ALTER TABLE ONLY "public"."Submission"
    ADD CONSTRAINT "Submission_assessmentId_fkey" FOREIGN KEY ("assessmentId") REFERENCES "public"."Assessment"("id");



ALTER TABLE ONLY "public"."Submission"
    ADD CONSTRAINT "Submission_studentId_fkey" FOREIGN KEY ("studentId") REFERENCES "public"."Student"("id");



ALTER TABLE ONLY "public"."Teacher"
    ADD CONSTRAINT "Teacher_userId_fkey" FOREIGN KEY ("userId") REFERENCES "public"."User"("id");



ALTER TABLE ONLY "public"."User"
    ADD CONSTRAINT "User_departmentId_fkey" FOREIGN KEY ("departmentId") REFERENCES "public"."Department"("id");



ALTER TABLE ONLY "public"."User"
    ADD CONSTRAINT "User_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id");



ALTER TABLE "public"."Admin" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";




















































































































































































GRANT ALL ON FUNCTION "public"."get_student_invoice_data"("term_input" "text", "amount" numeric, "desc_text" "text") TO "anon";
GRANT ALL ON FUNCTION "public"."get_student_invoice_data"("term_input" "text", "amount" numeric, "desc_text" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_student_invoice_data"("term_input" "text", "amount" numeric, "desc_text" "text") TO "service_role";



























GRANT ALL ON TABLE "public"."Admin" TO "anon";
GRANT ALL ON TABLE "public"."Admin" TO "authenticated";
GRANT ALL ON TABLE "public"."Admin" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Admin_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Admin_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Admin_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Assessment" TO "anon";
GRANT ALL ON TABLE "public"."Assessment" TO "authenticated";
GRANT ALL ON TABLE "public"."Assessment" TO "service_role";



GRANT ALL ON TABLE "public"."AssessmentFile" TO "anon";
GRANT ALL ON TABLE "public"."AssessmentFile" TO "authenticated";
GRANT ALL ON TABLE "public"."AssessmentFile" TO "service_role";



GRANT ALL ON SEQUENCE "public"."AssessmentFile_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."AssessmentFile_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."AssessmentFile_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Assessment_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Assessment_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Assessment_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Attendance" TO "anon";
GRANT ALL ON TABLE "public"."Attendance" TO "authenticated";
GRANT ALL ON TABLE "public"."Attendance" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Attendance_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Attendance_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Attendance_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Class" TO "anon";
GRANT ALL ON TABLE "public"."Class" TO "authenticated";
GRANT ALL ON TABLE "public"."Class" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Class_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Class_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Class_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Course" TO "anon";
GRANT ALL ON TABLE "public"."Course" TO "authenticated";
GRANT ALL ON TABLE "public"."Course" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Course_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Course_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Course_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Department" TO "anon";
GRANT ALL ON TABLE "public"."Department" TO "authenticated";
GRANT ALL ON TABLE "public"."Department" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Department_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Department_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Department_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Enrollment" TO "anon";
GRANT ALL ON TABLE "public"."Enrollment" TO "authenticated";
GRANT ALL ON TABLE "public"."Enrollment" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Enrollment_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Enrollment_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Enrollment_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Invoice" TO "anon";
GRANT ALL ON TABLE "public"."Invoice" TO "authenticated";
GRANT ALL ON TABLE "public"."Invoice" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Invoice_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Invoice_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Invoice_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Program" TO "anon";
GRANT ALL ON TABLE "public"."Program" TO "authenticated";
GRANT ALL ON TABLE "public"."Program" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Program_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Program_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Program_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Request" TO "anon";
GRANT ALL ON TABLE "public"."Request" TO "authenticated";
GRANT ALL ON TABLE "public"."Request" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Request_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Request_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Request_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Schedule" TO "anon";
GRANT ALL ON TABLE "public"."Schedule" TO "authenticated";
GRANT ALL ON TABLE "public"."Schedule" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Schedule_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Schedule_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Schedule_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Student" TO "anon";
GRANT ALL ON TABLE "public"."Student" TO "authenticated";
GRANT ALL ON TABLE "public"."Student" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Student_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Student_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Student_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Submission" TO "anon";
GRANT ALL ON TABLE "public"."Submission" TO "authenticated";
GRANT ALL ON TABLE "public"."Submission" TO "service_role";



GRANT ALL ON TABLE "public"."SubmissionFile" TO "anon";
GRANT ALL ON TABLE "public"."SubmissionFile" TO "authenticated";
GRANT ALL ON TABLE "public"."SubmissionFile" TO "service_role";



GRANT ALL ON SEQUENCE "public"."SubmissionFile_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."SubmissionFile_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."SubmissionFile_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Submission_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Submission_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Submission_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."Teacher" TO "anon";
GRANT ALL ON TABLE "public"."Teacher" TO "authenticated";
GRANT ALL ON TABLE "public"."Teacher" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Teacher_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Teacher_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Teacher_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."User" TO "anon";
GRANT ALL ON TABLE "public"."User" TO "authenticated";
GRANT ALL ON TABLE "public"."User" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";






























RESET ALL;
