name: Supabase Schema Sync

on:
  workflow_dispatch:

jobs:
  sync-schema:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Login with Supabase access token
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          npx supabase login --token $SUPABASE_ACCESS_TOKEN

      - name: Dump Supabase schema only
        env:
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_ID }}
        run: |
          mkdir -p supabase
          npx supabase db dump --file supabase/schema.sql --project-ref $SUPABASE_PROJECT_REF

      - name: Commit and push schema changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add supabase/schema.sql

          if git diff --cached --quiet; then
            echo "No changes detected in schema."
          else
            git commit -m "chore: update Supabase schema dump"
            git push
          fi
