name: Export Supabase Schema

on:
  workflow_dispatch:

jobs:
  dump-schema:
    name: Dump Supabase Schema
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Supabase CLI
        run: |
          curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt-get install -y nodejs
          npm install -g supabase

      - name: Set up Supabase credentials
        run: |
          supabase login --access-token "${{ secrets.SUPABASE_ACCESS_TOKEN }}"

      - name: Dump schema (no data)
        run: |
          mkdir -p supabase
          supabase db dump \
            --db-url "${{ secrets.SUPABASE_DB_URL }}" \
            --file supabase/schema.sql

      - name: Commit and push schema
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add supabase/schema.sql
          git commit -m "chore: update Supabase schema dump" || echo "No changes to commit"
          git push
