name: Supabase Schema Sync

on:
  workflow_dispatch:

jobs:
  sync-schema:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Login with Supabase access token
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          npx supabase login --token $SUPABASE_ACCESS_TOKEN

      - name: Dump Supabase schema only
        env:
          SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_DB_PASSWORD }}
        run: |
          mkdir -p supabase
          npx supabase db dump --file supabase/schema.sql --db-url postgresql://postgres.taakgxjwqeqziijeyoij:${SUPABASE_PROJECT_REF}@aws-0-us-west-1.pooler.supabase.com:6543/postgres

      - name: Upload schema.sql as artifact
        uses: actions/upload-artifact@v4
        with:
          name: supabase-schema
          path: supabase/schema.sql