name: Export Supabase Schema

on:
  workflow_dispatch:

jobs:
  pull-schema:
    runs-on: ubuntu-latest
    name: Export Supabase Schema and Commit
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js (required for Supabase CLI)
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Supabase CLI
        run: |
          npm install -g supabase

      - name: Login to Supabase
        run: supabase login --token ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Link to Supabase project
        run: supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_ID }}

      - name: Pull Supabase schema
        run: supabase db pull

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "chore: update Supabase schema"
          git push
